### ISSUE TITLE
Add spell checking

### ISSUE THREAD

**Issue by koppor** [a-nau/latex-devcontainer#1]
I would propose to add [LTeX – LanguageTool grammar/spell checking](https://marketplace.visualstudio.com/items?itemName=valentjn.vscode-ltex) as VS Code extension as it provides great spell checking experience.

Side note: Thank you for your package!  I am also basing on texlive-full at https://github.com/dante-ev/docker-texlive/blob/main/Dockerfile. Maybe, you get some inspiration? README on the additons: https://github.com/dante-ev/docker-texlive/blob/main/README.md

**Comment by a-nau** [comment]
Thanks @koppor for the hints, sounds very good! 
I'll check it these days and update the repo.

**Comment by a-nau** [comment]
Thanks again for your feedback and your work with dante-ev @koppor!

I added the VS code extension and also switched to your Docker image. It looks very good and I was actually already using it for the Github CI. 

I am closing this issue, but of course let me know if you have any other feedback :)

**Comment by koppor** [comment]
Hey, thank you for the feedback. I was about stopping maintenance of it, because the upstream texlive container has more maintainers. If you'd like to join forces at the danteev image, I would resume working on it.

Side note: Regarding minimal images (build time reduction!) I like the concept of https://github.com/reitzig/texlive-docker more. However, these images require adjustment for each document/project, which is a high barrier for newcomers.
